import test from "node:test";
import assert from "node:assert/strict";

import {
  LAUNCH_CODE_NO_RESTART_ON_CLEAN_EXIT,
  LAUNCH_CODE_PATH_OUTSIDE_LAYOUT,
  classifyGatewayLaunchUpdatability,
  isPathInside,
  launcherResolvesReleaseLayout,
  parseLaunchctlPrintCommand,
  parseLaunchctlPrintKeepAlive,
  parseLaunchctlPrintPlistPath,
  parseLaunchdKeepAlive,
  parseLaunchdProgramArguments,
  parseSystemctlShowProperties,
  parseSystemdExecStart,
  parseSystemdExecStartProperty,
  parseSystemdRestartPolicy,
  parseSystemdUnitFromCgroup,
  type GatewayLaunchCommandRunner,
} from "../update/gateway-launch-updatability";

/**
 * MAN-355, the half `d3d42ce11` could not reach: an ALREADY-supervised box.
 *
 * The unit contents below are not invented. They are what production
 * (165.227.25.201) actually carries, read on 2026-08-18 — including the
 * details that make it un-updatable in two independent ways: an ExecStart
 * outside the release layout, and `Restart=on-failure`, under which the
 * clean exit a self-update ends with leaves the box switched off rather than
 * starting the new build.
 *
 * The `systemctl show` fixtures are equally real: both the pre-repair and
 * post-repair renderings below were read off that same box (systemd 255),
 * structured `ExecStart={ path=… ; argv[]=… ; … }` shape included. That
 * matters more than usual here — the bug this file now covers is precisely
 * that the base unit FILE and what systemd actually runs are two different
 * things, so a fixture invented from the file could never have shown it.
 */

const PRODUCTION_UNIT = `[Unit]
Description=Empyralis Gateway (channels-via-gateway build - isolated instance)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=empyralis-gw
Group=empyralis-gw
EnvironmentFile=/etc/empyralis/gateway-channels.env
WorkingDirectory=/opt/empyralis-app/empyralis-gateway
ExecStart=/usr/bin/node /opt/empyralis-app/empyralis-gateway/dist/index.js
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
`;

const PRODUCTION_CGROUP = "0::/system.slice/empyralis-gateway-channels.service\n";
const PRODUCTION_UNIT_PATH = "/etc/systemd/system/empyralis-gateway-channels.service";

/** The launcher the gateway writes for itself (gateway-launch-repair.ts),
 *  copied from the real file on production rather than re-typed. */
const PRODUCTION_REPAIR_LAUNCHER = `#!/bin/sh
# Generated by the Empyralis gateway. Do not edit — it is rewritten on every
# start, and it deliberately holds no policy of its own.
set -eu

CANDIDATE='/var/lib/empyralis-gw/gateway-releases/current/gateway/dist/index.js'
FALLBACK='/opt/empyralis-app/empyralis-gateway/dist/index.js'
NODE='/usr/bin/node'

if [ -f "$CANDIDATE" ]; then
  entry="$CANDIDATE"
else
  entry="$FALLBACK"
fi

cd "$(dirname "$entry")"
exec "$NODE" "$entry"
`;

const SYSTEMD_ENV = { INVOCATION_ID: "abc123" } as NodeJS.ProcessEnv;

function readerFor(files: Record<string, string>) {
  return async (filePath: string): Promise<string> => {
    if (filePath in files) {
      return files[filePath];
    }
    const error = new Error(`ENOENT: ${filePath}`) as NodeJS.ErrnoException;
    error.code = "ENOENT";
    throw error;
  };
}

/** systemd 255's own rendering, verbatim in shape: one structured ExecStart
 *  carrying runtime status fields that must NOT leak into the command. */
function systemctlShowOutput(params: {
  program: string;
  argv: string;
  restart: string;
  fragmentPath?: string;
  dropIns?: string[];
}): string {
  return [
    `Restart=${params.restart}`,
    `ExecStart={ path=${params.program} ; argv[]=${params.argv} ; ignore_errors=no ; ` +
      "start_time=[Tue 2026-08-18 11:29:57 UTC] ; stop_time=[n/a] ; pid=2338249 ; " +
      "code=(null) ; status=0/0 }",
    `FragmentPath=${params.fragmentPath ?? PRODUCTION_UNIT_PATH}`,
    `DropInPaths=${(params.dropIns ?? []).join(" ")}`,
    "",
  ].join("\n");
}

function systemctlRunner(stdout: string): GatewayLaunchCommandRunner {
  return async (command, args) => {
    assert.equal(command, "systemctl");
    assert.equal(args[0], "show");
    return { exitCode: 0, stdout, stderr: "", timedOut: false };
  };
}

/** No systemctl/launchctl on PATH: execFileWithTimeout reports the spawn
 *  failure, which the default runner turns into a null exit code. */
const unavailableRunner: GatewayLaunchCommandRunner = async () => ({
  exitCode: null,
  stdout: "",
  stderr: "",
  timedOut: false,
});

test("THE BUG: a drop-in repairs a stale base unit, and the box is reported updatable", async () => {
  // Exactly production after docs/DEPLOY-RUNBOOK.md's repair was applied:
  // the base file still says `/usr/bin/node /opt/…` + `Restart=on-failure`,
  // and `…service.d/empyralis-updatable.conf` overrides both. Reading the
  // file reported "not_updatable" at a box that was already fixed.
  const result = await classifyGatewayLaunchUpdatability({
    env: SYSTEMD_ENV,
    platform: "linux",
    stateDir: "/var/lib/empyralis-gw/state",
    readFile: readerFor({
      "/proc/self/cgroup": PRODUCTION_CGROUP,
      [PRODUCTION_UNIT_PATH]: PRODUCTION_UNIT,
      "/var/lib/empyralis-gw/state/launch/run-gateway": PRODUCTION_REPAIR_LAUNCHER,
    }),
    runCommand: systemctlRunner(
      systemctlShowOutput({
        program: "/var/lib/empyralis-gw/state/launch/run-gateway",
        argv: "/var/lib/empyralis-gw/state/launch/run-gateway",
        restart: "always",
        dropIns: [
          "/etc/systemd/system/empyralis-gateway-channels.service.d/empyralis-updatable.conf",
        ],
      }),
    ),
  });

  assert.equal(result.status, "updatable");
  assert.deepEqual(result.blockers, []);
  assert.equal(result.configSource, "systemd-effective");
  assert.equal(result.launchCommand, "/var/lib/empyralis-gw/state/launch/run-gateway");
  // The operator is shown the override that is actually in force, not just
  // the base file that disagrees with it.
  assert.deepEqual(result.overridePaths, [
    "/etc/systemd/system/empyralis-gateway-channels.service.d/empyralis-updatable.conf",
  ]);
  assert.equal(result.unknownReason, null);
});

test("systemd's runtime status fields never leak into the command an operator is shown", async () => {
  const result = await classifyGatewayLaunchUpdatability({
    env: SYSTEMD_ENV,
    platform: "linux",
    stateDir: "/var/lib/empyralis-gw/state",
    readFile: readerFor({ "/proc/self/cgroup": PRODUCTION_CGROUP }),
    runCommand: systemctlRunner(
      systemctlShowOutput({
        program: "/usr/bin/node",
        argv: "/usr/bin/node /var/lib/empyralis-gw/gateway-releases/current/gateway/dist/index.js",
        restart: "always",
      }),
    ),
  });

  assert.equal(
    result.launchCommand,
    "/usr/bin/node /var/lib/empyralis-gw/gateway-releases/current/gateway/dist/index.js",
  );
  assert.equal(result.status, "updatable");
});

test("production's real PRE-REPAIR unit is reported as not updatable, naming BOTH blockers separately", async () => {
  const result = await classifyGatewayLaunchUpdatability({
    env: SYSTEMD_ENV,
    platform: "linux",
    stateDir: "/var/lib/empyralis-gw/state",
    readFile: readerFor({
      "/proc/self/cgroup": PRODUCTION_CGROUP,
      [PRODUCTION_UNIT_PATH]: PRODUCTION_UNIT,
    }),
    runCommand: systemctlRunner(
      systemctlShowOutput({
        program: "/usr/bin/node",
        argv: "/usr/bin/node /opt/empyralis-app/empyralis-gateway/dist/index.js",
        restart: "on-failure",
      }),
    ),
  });

  assert.equal(result.status, "not_updatable");
  assert.equal(result.unitPath, PRODUCTION_UNIT_PATH);
  assert.equal(
    result.launchCommand,
    "/usr/bin/node /opt/empyralis-app/empyralis-gateway/dist/index.js",
  );
  assert.equal(
    result.expectedEntrypoint,
    "/var/lib/empyralis-gw/gateway-releases/current/gateway/dist/index.js",
  );
  const codes = result.blockers.map((blocker) => blocker.code).sort();
  assert.deepEqual(codes, [LAUNCH_CODE_PATH_OUTSIDE_LAYOUT, LAUNCH_CODE_NO_RESTART_ON_CLEAN_EXIT].sort());
  // Two different facts, two different fixes — never one merged sentence.
  assert.equal(new Set(result.blockers.map((blocker) => blocker.detail)).size, 2);
  assert.equal(result.unknownReason, null);
  assert.equal(result.configSource, "systemd-effective");
});

test("with systemd unaskable, a base file that alone looks broken is UNKNOWN, never not_updatable", async () => {
  // The fallback cannot see a drop-in, and a drop-in is our own documented
  // repair — so a blocker derived from the file alone is unconfirmable.
  const result = await classifyGatewayLaunchUpdatability({
    env: SYSTEMD_ENV,
    platform: "linux",
    stateDir: "/var/lib/empyralis-gw/state",
    readFile: readerFor({
      "/proc/self/cgroup": PRODUCTION_CGROUP,
      [PRODUCTION_UNIT_PATH]: PRODUCTION_UNIT,
    }),
    runCommand: unavailableRunner,
  });

  assert.equal(result.status, "unknown");
  assert.equal(result.configSource, "systemd-unit-file");
  assert.ok(result.unknownReason);
  assert.deepEqual(result.blockers, []);
  // The operator still gets the two facts they would act on.
  assert.equal(result.unitPath, PRODUCTION_UNIT_PATH);
  assert.equal(
    result.launchCommand,
    "/usr/bin/node /opt/empyralis-app/empyralis-gateway/dist/index.js",
  );
});

test("with systemd unaskable, a base file that looks FINE still answers updatable", async () => {
  const result = await classifyGatewayLaunchUpdatability({
    env: SYSTEMD_ENV,
    platform: "linux",
    stateDir: "/var/lib/empyralis-gw/state",
    readFile: readerFor({
      "/proc/self/cgroup": PRODUCTION_CGROUP,
      [PRODUCTION_UNIT_PATH]: [
        "[Service]",
        "ExecStart=/usr/bin/node /var/lib/empyralis-gw/gateway-releases/current/gateway/dist/index.js",
        "Restart=always",
      ].join("\n"),
    }),
    runCommand: unavailableRunner,
  });

  assert.equal(result.status, "updatable");
  assert.equal(result.configSource, "systemd-unit-file");
});

test("a unit systemd has never heard of is unknown — its printed Restart=no is not an answer", async () => {
  // Measured on production, systemd 255: `systemctl show <missing>.service`
  // exits 0 and prints `Restart=no` with no ExecStart at all. Trusting that
  // would manufacture a restart blocker for a unit that does not exist.
  const result = await classifyGatewayLaunchUpdatability({
    env: SYSTEMD_ENV,
    platform: "linux",
    stateDir: "/var/lib/empyralis-gw/state",
    readFile: readerFor({ "/proc/self/cgroup": PRODUCTION_CGROUP }),
    runCommand: async () => ({ exitCode: 0, stdout: "Restart=no\n", stderr: "", timedOut: false }),
  });

  assert.equal(result.status, "unknown");
  assert.deepEqual(result.blockers, []);
});

test("a systemctl query that hangs past the deadline is unknown, not a verdict", async () => {
  const result = await classifyGatewayLaunchUpdatability({
    env: SYSTEMD_ENV,
    platform: "linux",
    stateDir: "/var/lib/empyralis-gw/state",
    readFile: readerFor({
      "/proc/self/cgroup": PRODUCTION_CGROUP,
      [PRODUCTION_UNIT_PATH]: PRODUCTION_UNIT,
    }),
    runCommand: async () => ({ exitCode: null, stdout: "", stderr: "", timedOut: true }),
  });

  assert.equal(result.status, "unknown");
});

test("a runner that THROWS is unknown, never a verdict", async () => {
  const result = await classifyGatewayLaunchUpdatability({
    env: SYSTEMD_ENV,
    platform: "linux",
    stateDir: "/var/lib/empyralis-gw/state",
    readFile: readerFor({
      "/proc/self/cgroup": PRODUCTION_CGROUP,
      [PRODUCTION_UNIT_PATH]: PRODUCTION_UNIT,
    }),
    runCommand: async () => {
      throw new Error("boom");
    },
  });

  assert.equal(result.status, "unknown");
  assert.deepEqual(result.blockers, []);
});

test("an installer-provisioned box, whose launcher resolves the layout at start, is updatable", async () => {
  const runGateway = `#!/usr/bin/env bash
set -Eeuo pipefail
SELF_UPDATE_INSTALL_ROOT="\${EMPYRALIS_GATEWAY_INSTALL_ROOT:-}"
if [[ -n "\${SELF_UPDATE_INSTALL_ROOT}" && -f "\${SELF_UPDATE_INSTALL_ROOT}/current/gateway/dist/index.js" ]]; then
  entry="\${SELF_UPDATE_INSTALL_ROOT}/current/gateway/dist/index.js"
fi
exec node "\${entry}"
`;
  const result = await classifyGatewayLaunchUpdatability({
    env: SYSTEMD_ENV,
    platform: "linux",
    stateDir: "/var/lib/empyralis/agent-computer/gateway",
    readFile: readerFor({
      "/proc/self/cgroup": "0::/system.slice/empyralis-gateway.service\n",
      "/etc/systemd/system/empyralis-gateway.service": [
        "[Service]",
        "ExecStart=/opt/empyralis/agent-computer/bin/run-gateway",
        "Restart=always",
      ].join("\n"),
      "/opt/empyralis/agent-computer/bin/run-gateway": runGateway,
    }),
    runCommand: systemctlRunner(
      systemctlShowOutput({
        program: "/opt/empyralis/agent-computer/bin/run-gateway",
        argv: "/opt/empyralis/agent-computer/bin/run-gateway",
        restart: "always",
        fragmentPath: "/etc/systemd/system/empyralis-gateway.service",
      }),
    ),
  });

  assert.equal(result.status, "updatable");
  assert.deepEqual(result.blockers, []);
});

test("an OLD launcher — one predating the release-layout block — is correctly reported stuck", async () => {
  const oldRunGateway = `#!/usr/bin/env bash
set -Eeuo pipefail
INSTALL_DIR="/opt/empyralis/agent-computer/current"
exec node "\${INSTALL_DIR}/gateway/dist/index.js"
`;
  const result = await classifyGatewayLaunchUpdatability({
    env: SYSTEMD_ENV,
    platform: "linux",
    stateDir: "/var/lib/empyralis/agent-computer/gateway",
    readFile: readerFor({
      "/proc/self/cgroup": "0::/system.slice/empyralis-gateway.service\n",
      "/etc/systemd/system/empyralis-gateway.service": [
        "[Service]",
        "ExecStart=/opt/empyralis/agent-computer/bin/run-gateway",
        "Restart=always",
      ].join("\n"),
      "/opt/empyralis/agent-computer/bin/run-gateway": oldRunGateway,
    }),
    runCommand: systemctlRunner(
      systemctlShowOutput({
        program: "/opt/empyralis/agent-computer/bin/run-gateway",
        argv: "/opt/empyralis/agent-computer/bin/run-gateway",
        restart: "always",
        fragmentPath: "/etc/systemd/system/empyralis-gateway.service",
      }),
    ),
  });

  assert.equal(result.status, "not_updatable");
  assert.deepEqual(
    result.blockers.map((blocker) => blocker.code),
    [LAUNCH_CODE_PATH_OUTSIDE_LAYOUT],
  );
});

test("a unit pointing straight into the release layout is updatable without any launcher script", async () => {
  const result = await classifyGatewayLaunchUpdatability({
    env: SYSTEMD_ENV,
    platform: "linux",
    stateDir: "/var/lib/empyralis-gw/state",
    readFile: readerFor({
      "/proc/self/cgroup": PRODUCTION_CGROUP,
      [PRODUCTION_UNIT_PATH]: [
        "[Service]",
        "ExecStart=/usr/bin/node /var/lib/empyralis-gw/gateway-releases/current/gateway/dist/index.js",
        "Restart=always",
      ].join("\n"),
    }),
    runCommand: systemctlRunner(
      systemctlShowOutput({
        program: "/usr/bin/node",
        argv: "/usr/bin/node /var/lib/empyralis-gw/gateway-releases/current/gateway/dist/index.js",
        restart: "always",
      }),
    ),
  });

  assert.equal(result.status, "updatable");
});

test("EVERY way of not knowing resolves to unknown, never to not_updatable", async () => {
  const unsupervised = await classifyGatewayLaunchUpdatability({
    env: {},
    platform: "linux",
    stateDir: "/var/lib/empyralis-gw/state",
    readFile: readerFor({}),
    runCommand: unavailableRunner,
  });
  assert.equal(unsupervised.status, "unknown");
  assert.ok(unsupervised.unknownReason);

  const noStateDir = await classifyGatewayLaunchUpdatability({
    env: SYSTEMD_ENV,
    platform: "linux",
    readFile: readerFor({}),
    runCommand: unavailableRunner,
  });
  assert.equal(noStateDir.status, "unknown");

  const unreadableUnit = await classifyGatewayLaunchUpdatability({
    env: SYSTEMD_ENV,
    platform: "linux",
    stateDir: "/var/lib/empyralis-gw/state",
    readFile: readerFor({ "/proc/self/cgroup": PRODUCTION_CGROUP }),
    runCommand: unavailableRunner,
  });
  assert.equal(unreadableUnit.status, "unknown");

  const noExecStart = await classifyGatewayLaunchUpdatability({
    env: SYSTEMD_ENV,
    platform: "linux",
    stateDir: "/var/lib/empyralis-gw/state",
    readFile: readerFor({
      "/proc/self/cgroup": PRODUCTION_CGROUP,
      [PRODUCTION_UNIT_PATH]: "[Service]\nRestart=always\n",
    }),
    runCommand: unavailableRunner,
  });
  assert.equal(noExecStart.status, "unknown");
});

test("a probe that throws for EVERY path — including /proc — still answers, and answers unknown", async () => {
  const result = await classifyGatewayLaunchUpdatability({
    env: SYSTEMD_ENV,
    platform: "linux",
    stateDir: "/var/lib/empyralis-gw/state",
    readFile: async () => {
      throw new Error("boom");
    },
    runCommand: unavailableRunner,
  });
  assert.equal(result.status, "unknown");
  assert.deepEqual(result.blockers, []);
});

test("an unsupported platform is unknown, not a claim about updatability", async () => {
  const result = await classifyGatewayLaunchUpdatability({
    env: { INVOCATION_ID: "x" },
    platform: "win32",
    stateDir: "C:/state",
    readFile: readerFor({}),
    runCommand: unavailableRunner,
  });
  assert.equal(result.status, "unknown");
});

test("a launchd plist pinned outside the layout, with no KeepAlive, reports both blockers", async () => {
  const plist = `<?xml version="1.0" encoding="UTF-8"?>
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>ai.empyralis.agent-computer</string>
  <key>ProgramArguments</key>
  <array>
    <string>/usr/local/bin/node</string>
    <string>/Users/someone/checkout/empyralis-gateway/dist/index.js</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
</dict>
</plist>
`;
  const result = await classifyGatewayLaunchUpdatability({
    env: { EMPYRALIS_LAUNCHD_LABEL: "ai.empyralis.agent-computer" },
    platform: "darwin",
    homeDir: "/Users/someone",
    stateDir: "/Users/someone/.empyralis/gateway",
    readFile: readerFor({
      "/Users/someone/Library/LaunchAgents/ai.empyralis.agent-computer.plist": plist,
    }),
    runCommand: unavailableRunner,
  });

  assert.equal(result.status, "not_updatable");
  assert.equal(result.configSource, "launchd-plist-file");
  assert.deepEqual(
    result.blockers.map((blocker) => blocker.code).sort(),
    [LAUNCH_CODE_PATH_OUTSIDE_LAYOUT, LAUNCH_CODE_NO_RESTART_ON_CLEAN_EXIT].sort(),
  );
});

test("a launchd plist with KeepAlive true, pointing into the layout, is updatable", async () => {
  const plist = `<?xml version="1.0" encoding="UTF-8"?>
<plist version="1.0">
<dict>
  <key>ProgramArguments</key>
  <array>
    <string>/usr/local/bin/node</string>
    <string>/Users/someone/.empyralis/gateway-releases/current/gateway/dist/index.js</string>
  </array>
  <key>KeepAlive</key>
  <true/>
</dict>
</plist>
`;
  const result = await classifyGatewayLaunchUpdatability({
    env: { EMPYRALIS_LAUNCHD_LABEL: "ai.empyralis.agent-computer" },
    platform: "darwin",
    homeDir: "/Users/someone",
    stateDir: "/Users/someone/.empyralis/gateway",
    readFile: readerFor({
      "/Users/someone/Library/LaunchAgents/ai.empyralis.agent-computer.plist": plist,
    }),
    runCommand: unavailableRunner,
  });
  assert.equal(result.status, "updatable");
});

test("launchd: the LOADED job decides, not a plist edited underneath it", async () => {
  // launchd has no drop-ins, but it does hold the job as bootstrapped — so a
  // plist edited (or replaced) after load is not what starts the next
  // process. The file here looks stuck; the loaded job is repaired.
  const stalePlist = `<?xml version="1.0" encoding="UTF-8"?>
<plist version="1.0">
<dict>
  <key>ProgramArguments</key>
  <array>
    <string>/usr/local/bin/node</string>
    <string>/Users/someone/checkout/empyralis-gateway/dist/index.js</string>
  </array>
</dict>
</plist>
`;
  const loadedPlist = `<?xml version="1.0" encoding="UTF-8"?>
<plist version="1.0">
<dict>
  <key>KeepAlive</key>
  <true/>
</dict>
</plist>
`;
  const printOutput = `gui/501/ai.empyralis.agent-computer = {
\tactive count = 1
\tpath = /Users/someone/Library/LaunchAgents/ai.empyralis.agent-computer.loaded.plist
\ttype = LaunchAgent
\tstate = running

\tprogram = /usr/local/bin/node
\targuments = {
\t\t/usr/local/bin/node
\t\t/Users/someone/.empyralis/gateway-releases/current/gateway/dist/index.js
\t}

\tdomain = gui/501 [100014]
}
`;
  const result = await classifyGatewayLaunchUpdatability({
    env: { EMPYRALIS_LAUNCHD_LABEL: "ai.empyralis.agent-computer" },
    platform: "darwin",
    homeDir: "/Users/someone",
    uid: 501,
    stateDir: "/Users/someone/.empyralis/gateway",
    readFile: readerFor({
      "/Users/someone/Library/LaunchAgents/ai.empyralis.agent-computer.plist": stalePlist,
      "/Users/someone/Library/LaunchAgents/ai.empyralis.agent-computer.loaded.plist": loadedPlist,
    }),
    runCommand: async (command, args) => {
      assert.equal(command, "launchctl");
      assert.deepEqual(args, ["print", "gui/501/ai.empyralis.agent-computer"]);
      return { exitCode: 0, stdout: printOutput, stderr: "", timedOut: false };
    },
  });

  assert.equal(result.status, "updatable");
  assert.equal(result.configSource, "launchd-effective");
  assert.equal(
    result.launchCommand,
    "/usr/local/bin/node /Users/someone/.empyralis/gateway-releases/current/gateway/dist/index.js",
  );
  // launchd carries nothing layered over a job, so this stays empty and the
  // field never implies a mechanism that does not exist on this platform.
  assert.deepEqual(result.overridePaths, []);
});

test("launchd: a per-user domain miss falls through to the system domain", async () => {
  const printOutput = `system/ai.empyralis.agent-computer = {
\tpath = /Library/LaunchDaemons/ai.empyralis.agent-computer.plist
\tprogram = /usr/local/bin/node
\targuments = {
\t\t/usr/local/bin/node
\t\t/Users/someone/checkout/empyralis-gateway/dist/index.js
\t}
\tproperties = keepalive | runatload
}
`;
  const asked: string[] = [];
  const result = await classifyGatewayLaunchUpdatability({
    env: { EMPYRALIS_LAUNCHD_LABEL: "ai.empyralis.agent-computer" },
    platform: "darwin",
    homeDir: "/Users/someone",
    uid: 501,
    stateDir: "/Users/someone/.empyralis/gateway",
    readFile: readerFor({}),
    runCommand: async (_command, args) => {
      asked.push(args[1]);
      if (args[1].startsWith("gui/")) {
        return { exitCode: 113, stdout: "", stderr: "Could not find service", timedOut: false };
      }
      return { exitCode: 0, stdout: printOutput, stderr: "", timedOut: false };
    },
  });

  assert.deepEqual(asked, [
    "gui/501/ai.empyralis.agent-computer",
    "system/ai.empyralis.agent-computer",
  ]);
  assert.equal(result.configSource, "launchd-effective");
  // The path is genuinely outside the layout — that blocker is real. The
  // KeepAlive one is not, because the loaded job reports keepalive.
  assert.deepEqual(
    result.blockers.map((blocker) => blocker.code),
    [LAUNCH_CODE_PATH_OUTSIDE_LAYOUT],
  );
});

test("parsers: the shapes systemd and launchd actually produce", () => {
  assert.equal(
    parseSystemdUnitFromCgroup("0::/system.slice/empyralis-gateway-channels.service\n"),
    "empyralis-gateway-channels.service",
  );
  assert.equal(parseSystemdUnitFromCgroup("0::/user.slice/session-3.scope\n"), null);

  // systemd's own ExecStart prefixes must not leak into the command.
  assert.equal(parseSystemdExecStart("[Service]\nExecStart=-/usr/bin/node /a.js"), "/usr/bin/node /a.js");
  assert.equal(parseSystemdExecStart("[Service]\nExecStart=+/usr/bin/node /a.js"), "/usr/bin/node /a.js");
  assert.equal(
    parseSystemdExecStart("[Service]\nExecStart=/usr/bin/node \\\n  /a.js"),
    "/usr/bin/node /a.js",
  );
  assert.equal(parseSystemdExecStart("[Service]\nRestart=always"), null);

  // Last assignment wins, matching systemd's own parsing.
  assert.equal(parseSystemdRestartPolicy("Restart=no\nRestart=always"), "always");
  assert.equal(parseSystemdRestartPolicy("[Service]\nType=simple"), null);

  assert.deepEqual(
    parseLaunchdProgramArguments(
      "<key>ProgramArguments</key><array><string>/bin/node</string><string>/a.js</string></array>",
    ),
    ["/bin/node", "/a.js"],
  );
  assert.deepEqual(parseLaunchdProgramArguments("<plist></plist>"), []);
  assert.equal(parseLaunchdKeepAlive("<key>KeepAlive</key><true/>"), true);
  assert.equal(parseLaunchdKeepAlive("<key>KeepAlive</key><false/>"), false);
  // A KeepAlive DICT is conditional, so it is not a promise that a
  // deliberate exit comes back.
  assert.equal(
    parseLaunchdKeepAlive("<key>KeepAlive</key><dict><key>Crashed</key><true/></dict>"),
    false,
  );
});

test("parsers: `systemctl show`'s structured ExecStart, read off production", () => {
  const properties = parseSystemctlShowProperties(
    systemctlShowOutput({
      program: "/var/lib/empyralis-gw/state/launch/run-gateway",
      argv: "/var/lib/empyralis-gw/state/launch/run-gateway",
      restart: "always",
      dropIns: ["/etc/systemd/system/x.service.d/a.conf", "/etc/systemd/system/x.service.d/b.conf"],
    }),
  );
  assert.deepEqual(properties.get("Restart"), ["always"]);
  assert.equal(properties.get("ExecStart")?.length, 1);

  // argv[] wins, and the ` ; `-separated runtime status after it is dropped.
  assert.equal(
    parseSystemdExecStartProperty(properties.get("ExecStart")![0]),
    "/var/lib/empyralis-gw/state/launch/run-gateway",
  );
  assert.equal(
    parseSystemdExecStartProperty(
      "{ path=/usr/bin/node ; argv[]=/usr/bin/node /a.js ; ignore_errors=no ; pid=1 }",
    ),
    "/usr/bin/node /a.js",
  );
  // path= is the fallback when a shape carries no argv.
  assert.equal(
    parseSystemdExecStartProperty("{ path=/usr/bin/node ; ignore_errors=no }"),
    "/usr/bin/node",
  );
  // An unstructured value (an older systemd) is still an answer.
  assert.equal(parseSystemdExecStartProperty("/usr/bin/node /a.js"), "/usr/bin/node /a.js");
  assert.equal(parseSystemdExecStartProperty(""), null);

  // A repeated key keeps every value, in order — a unit may declare several.
  const repeated = parseSystemctlShowProperties("ExecStart=a\nExecStart=b\nRestart=always\n");
  assert.deepEqual(repeated.get("ExecStart"), ["a", "b"]);

  // A path containing '=' survives: only the FIRST '=' separates key from value.
  const oddValue = parseSystemctlShowProperties("FragmentPath=/etc/systemd/system/a=b.service\n");
  assert.deepEqual(oddValue.get("FragmentPath"), ["/etc/systemd/system/a=b.service"]);
});

test("parsers: `launchctl print`'s own shape", () => {
  const output = `gui/501/x = {
\tpath = /Users/x/Library/LaunchAgents/x.plist
\tprogram = /usr/local/bin/node
\targuments = {
\t\t/usr/local/bin/node
\t\t/opt/a.js
\t}
\tproperties = keepalive | runatload | system service
}
`;
  assert.equal(parseLaunchctlPrintCommand(output), "/usr/local/bin/node /opt/a.js");
  assert.equal(parseLaunchctlPrintPlistPath(output), "/Users/x/Library/LaunchAgents/x.plist");
  assert.equal(parseLaunchctlPrintKeepAlive(output), true);

  // `program` alone is the shape for a job declared without an argv, and is
  // the only fallback — never a guess.
  assert.equal(
    parseLaunchctlPrintCommand("gui/501/x = {\n\tprogram = /usr/local/bin/foo\n}\n"),
    "/usr/local/bin/foo",
  );
  assert.equal(parseLaunchctlPrintCommand("gui/501/x = {\n}\n"), null);

  // The keepalive token is POSITIVE-ONLY: its absence must not be read as a
  // promise that the job will not come back, or a healthy Mac gets a blocker
  // manufactured for it out of a token Apple never documented.
  assert.equal(
    parseLaunchctlPrintKeepAlive("gui/501/x = {\n\tproperties = runatload | system service\n}\n"),
    false,
  );
  assert.equal(parseLaunchctlPrintKeepAlive("gui/501/x = {\n}\n"), false);
  // The per-endpoint `keepalive = 0` lines launchctl prints inside its
  // endpoint blocks are NOT the job's KeepAlive and must not be read as it.
  assert.equal(
    parseLaunchctlPrintKeepAlive(
      "gui/501/x = {\n\tendpoints = {\n\t\t\"y\" = {\n\t\t\tkeepalive = 0\n\t\t}\n\t}\n}\n",
    ),
    false,
  );
});

test("path containment does not match a sibling directory that merely shares a prefix", () => {
  assert.equal(isPathInside("/var/lib/gw", "/var/lib/gw/releases/1"), true);
  assert.equal(isPathInside("/var/lib/gw", "/var/lib/gw"), true);
  assert.equal(isPathInside("/var/lib/gw", "/var/lib/gw-old/releases/1"), false);
  assert.equal(isPathInside("/var/lib/gw", "/opt/app/dist/index.js"), false);
});

test("a launcher is only credited when it BOTH tests the layout entrypoint and derives the root", () => {
  assert.equal(
    launcherResolvesReleaseLayout(
      '#!/bin/sh\n[ -f "$R/current/gateway/dist/index.js" ] && exec node "$R/current/gateway/dist/index.js"\nEMPYRALIS_GATEWAY_INSTALL_ROOT=x\n',
    ),
    true,
  );
  // Mentions the root but never resolves through it.
  assert.equal(
    launcherResolvesReleaseLayout("#!/bin/sh\nEMPYRALIS_GATEWAY_INSTALL_ROOT=x\nexec node /opt/a.js\n"),
    false,
  );
  // A binary must never be sniffed as a launcher.
  assert.equal(
    launcherResolvesReleaseLayout("\x7fELF...gateway-releases/current/gateway/dist/index.js"),
    false,
  );
});
