import { GENERATED_OPENCLAW_ACTIVE_CHANNEL_IDS } from "./generated-openclaw-channels";

/**
 * The gateway-side half of channel_lane_contract_service.
 * OPENCLAW_TRANSPORT_OWNERSHIP — the ONE place, in the whole system, that
 * decides whether a platform's personal-channel traffic is owned by
 * Empyralis's own first-party runtime (WhatsAppPersonalRuntime,
 * TelegramPersonalRuntime, the local-bridge family) or by the OpenClaw
 * transport. That decision is made exactly once, in Python
 * (server_modules/openclaw_channel_registry.OPENCLAW_CUT_OVER_CHANNEL_IDS —
 * "the one authored datum in this module, and it is a DECISION"), and
 * reaches every other consumer — provisioning
 * (openclaw_provisioning_service.build_openclaw_channel_policies), inbound
 * routing (personal_channels_service.OPENCLAW_PERSONAL_CHANNELS), and the
 * gateway's own OpenClaw-side capability advertisement/runtime registration
 * (capabilities.ts's OPENCLAW_TRANSPORT_CHANNEL_IDS, outbound-runtime.ts's
 * buildOpenClawPersonalChannelRuntimes) — through ONE generated, drift-
 * tested artifact: generated-openclaw-channels.ts, regenerated by
 * scripts/generate_openclaw_channel_manifest.py and checked against the
 * Python side by server_modules/tests/test_openclaw_channel_registry.py.
 *
 * Every one of those consumers already reads that generated file. This
 * module closes the ONE gap: index.ts's main() constructed the first-party
 * personal-channel runtimes unconditionally (gated only on
 * config.personalChannelsEnabled, a single flag with no per-channel
 * awareness), with no reference to ownership at all — the only place in the
 * whole chain holding no opinion, rather than a second, drifting one. This
 * file adds no new authority: it reads GENERATED_OPENCLAW_ACTIVE_CHANNEL_IDS
 * — the set OpenClaw is the LIVE implementation of, i.e. exactly the
 * platforms present in OPENCLAW_CUT_OVER_CHANNEL_IDS — and translates a
 * first-party channel_key into the OpenClaw platform id that set is keyed
 * on. (NOT GENERATED_OPENCLAW_SUPERSEDED_CHANNEL_IDS — that array's name is
 * from OpenClaw's own point of view: an entry there means OpenClaw's
 * channel is dormant because Empyralis's first-party runtime still owns the
 * platform, the OPPOSITE of "cut over". Reading it here would have inverted
 * every decision this module makes; caught before this ever ran.)
 *
 * While OPENCLAW_CUT_OVER_CHANNEL_IDS is empty (true as of 2026-08-14),
 * GENERATED_OPENCLAW_ACTIVE_CHANNEL_IDS contains none of the platforms any
 * first-party personal-channel candidate maps to, so
 * activeFirstPartyPersonalChannels() is a strict identity filter today —
 * proven by __tests__/first-party-transport-ownership-gate.test.ts against
 * the REAL generated constant, plus a second test that simulates a future
 * cutover (via the optional `activeChannelIds` parameter below, never by
 * mutating the generated file) to prove the exclusion actually fires. Moving
 * a platform into OPENCLAW_CUT_OVER_CHANNEL_IDS (a decision, not made by
 * this file — see that constant's own doc, and the "same change" invariant
 * it states) and regenerating is what turns this into a real gate for that
 * one channel, with no further gateway code required — that is the entire
 * point of landing this now rather than at the moment of the first real
 * cutover.
 */

/**
 * Empyralis channel_key -> OpenClaw platform id, for the one first-party
 * personal channel whose id does not equal its own channel_key with a
 * "_personal"/"_official"/"_bot" suffix stripped. Mirrors
 * server_modules/openclaw_channel_registry.PLATFORM_TOKEN_TO_OPENCLAW_ID
 * EXACTLY — a genuine cross-language duplicate, the same class CLAUDE.md
 * already documents as unavoidable for the OpenClaw channel list itself
 * (e.g. LOCAL_BRIDGE_PERSONAL_CHANNELS existing in both
 * server_modules/personal_channels_service.py and
 * empyralis-gateway/src/channels/local-bridge-runtime.ts). It does not
 * decide ownership — only how to NAME the platform once the generated set
 * already has. Kept intentionally tiny: everything else matches by
 * stripping the suffix. An unmapped/unrecognized platform id simply never
 * matches GENERATED_OPENCLAW_ACTIVE_CHANNEL_IDS, so a channel this map
 * doesn't know about fails toward KEEPING today's first-party behavior,
 * never toward silently dropping it.
 */
const CHANNEL_KEY_PLATFORM_ID_OVERRIDES: Readonly<Record<string, string>> = {
  // Consumer WeChat, what Empyralis's wechat_personal local-bridge channel
  // talks to. Not "wecom" (WeChat Work — a different product; see
  // PLATFORM_TOKEN_TO_OPENCLAW_ID's own Python-side comment).
  wechat_personal: "openclaw-weixin",
};

const PERSONAL_CHANNEL_KEY_SUFFIXES = ["_personal", "_official", "_bot"] as const;

/**
 * Empyralis channel_key -> the bare platform id
 * GENERATED_OPENCLAW_ACTIVE_CHANNEL_IDS is keyed on. Exported for direct
 * unit testing.
 */
export function openClawPlatformIdForChannelKey(channelKey: string): string {
  const trimmed = String(channelKey || "").trim().toLowerCase();
  const override = CHANNEL_KEY_PLATFORM_ID_OVERRIDES[trimmed];
  if (override) {
    return override;
  }
  for (const suffix of PERSONAL_CHANNEL_KEY_SUFFIXES) {
    if (trimmed.endsWith(suffix)) {
      return trimmed.slice(0, -suffix.length);
    }
  }
  return trimmed;
}

/**
 * True when this channel_key's platform has been cut over to the OpenClaw
 * transport — i.e. the first-party runtime for it must NOT be constructed.
 * `activeChannelIds` defaults to the real generated
 * GENERATED_OPENCLAW_ACTIVE_CHANNEL_IDS; the parameter exists ONLY so a
 * test can simulate a future cutover without mutating the generated file —
 * production code never passes it.
 */
export function isFirstPartyChannelOwnedByOpenClaw(
  channelKey: string,
  activeChannelIds: readonly string[] = GENERATED_OPENCLAW_ACTIVE_CHANNEL_IDS,
): boolean {
  const platformId = openClawPlatformIdForChannelKey(channelKey);
  return activeChannelIds.includes(platformId);
}

/**
 * Filters a list of first-party personal-channel candidates down to the
 * ones that should actually be constructed right now. This is the ONE gate
 * every first-party personal-channel runtime in index.ts's main() goes
 * through — never a per-channel `if` — so a future cutover (flipping one
 * platform into OPENCLAW_CUT_OVER_CHANNEL_IDS and regenerating) needs no
 * new gateway code at all.
 */
export function activeFirstPartyPersonalChannels<T extends { channelKey: string }>(
  candidates: readonly T[],
  activeChannelIds: readonly string[] = GENERATED_OPENCLAW_ACTIVE_CHANNEL_IDS,
): T[] {
  return candidates.filter((candidate) => !isFirstPartyChannelOwnedByOpenClaw(candidate.channelKey, activeChannelIds));
}
